version: "3"
services:
  app: &app_base
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - bundle:/app/.bundle
      - tmp:/app/tmp
      - log:/app/log
    ports:
      - 3000:3000
    depends_on:
      - db
    tty: true
    stdin_open: true
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "1"
  db:
    image: postgres:9.3
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - 5433:5432
    volumes:
      - psgl_data:/var/lib/postgresql/data
volumes:
  psgl_data:
  bundle:
  tmp:
  log:
