version: "3"
services:
  app: &app_base
    build:
      context: .
      dockerfile: Dockerfile.dev
    # env_file:
    #   - ./.env.dev
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - bundle:/app/.bundle
      - node_modules:/app/node_modules
      - tmp:/app/tmp
      - log:/app/log
    ports:
      - 3000:3000
    depends_on:
      - db
    tty: true
    stdin_open: true
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "1"
  webpack:
    <<: *app_base
    command: /bin/sh -c "rm -rf /app/public/packs && bin/webpack-dev-server"
    ports:
      - 3035:3035
    depends_on:
      - app
    tty: false
    stdin_open: false
  db:
    image: mysql:5.7.26
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - 33906:3306
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
  bundle:
  node_modules:
  tmp:
  log:
